Added an initial setup instructions section
dupontgu/retro-ipod-spotify-client pull request #2
Opened 2021-01-30 09:56 UTC by utkut

I have added a simple instructions section based on the information from the hackaday project page. There are some of the install details missing, but this might be a good start for other users.

2021-01-31 14:16 UTC, dupontgu requested changes
Some tiny things! Thanks so much for doing this!

2021-01-31 14:16 UTC, dupontgu commented on README.md
> +sudo apt-get install python3-pigpio
Don't actually use pigpio from python, you can delete this line. Good thought though.

2021-01-31 14:16 UTC, dupontgu commented on README.md
> +cd openbox
Looks like there's a step missing? Also, I believe I simply used apt to install openbox. Totally cool to link to the source though

2021-01-31 18:29 UTC, utkut reviewed
Thanks for adding the missing steps.

2021-01-31 20:58 UTC, dupontgu approved these changes
This is awesome, thanks!

2021-02-06 16:38 UTC, rsappia commented
silly point, but missing :

`sudo apt-get install git`

2021-02-18 14:59 UTC, merged